version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "4000:4000"

  backend:
    extends:
      file: ../backend/docker-compose.yml
      service: api
